const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIDED: 'FETCH_GENDER_FAIDED',


    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILDED: 'FETCH_POSITION_FAILDED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAILDED',


    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAILDED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILDED: 'EDIT_USER_FAILDED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILDED: 'DELETE_USER_FAILDED',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILDED: 'FETCH_ALL_USER_FAILDED',

    


    FETCH_TYPE_START: 'FETCH_TYPE_START',
    FETCH_TYPE_SUCCESS: 'FETCH_TYPE_SUCCESS',
    FETCH_TYPE_FAILDED: 'FETCH_TYPE_FAILDED',


    FETCH_STATUS_START: 'FETCH_STATUS_START',
    FETCH_STATUS_SUCCESS: 'FETCH_STATUS_SUCCESS',
    FETCH_STATUS_FAILDED: 'FETCH_STATUS_FAILDED',


    CREATE_CAR_SUCCESS: 'CREATE_CAR_SUCCESS',
    CREATE_CAR_FAILED: 'CREATE_CAR_FAILED',

    FETCH_ALL_CAR_SUCCESS: 'FETCH_ALL_CAR_SUCCESS',
    FETCH_ALL_CAR_FAILED: 'FETCH_ALL_CAR_FAILED',

    EDIT_CAR_SUCCESS: 'EDIT_CAR_SUCCESS',
    EDIT_CAR_FAILED: 'EDIT_CAR_FAILED',

    DELETE_CAR_SUCCESS: 'DELETE_CAR_SUCCESS',
    DELETE_CAR_FAILED: 'DELETE_CAR_FAILED',

})

export default actionTypes;